apiVersion: 1

datasources:
  - name: grafanacloud-jacoboluengass-prom
    type: prometheus
    access: proxy
    url: https://better-billi-zugarez-sys-ed7b78de.koyeb.app/actuator/prometheus
    basicAuth: false
    editable: true
    jsonData:
      httpMethod: GET
